# Project information
site_name: k3d
site_description: Little helper to run Rancher Lab's k3s in Docker
site_url: https://k3d.io/

copyright: "Copyright &copy; 2020-2023 k3d Authors"

# Extra Files
extra_javascript:
  - static/js/asciinema-player.js

extra_css:
  - static/css/asciinema-player.css
  - static/css/extra.css

# Repo Information
repo_name: k3d-io/k3d
repo_url: https://github.com/k3d-io/k3d

# Edit Link on Site
edit_uri: edit/main/docs/

# Theme
theme:
  name: material
  language: en
  features:
    - navigation.top # show back to top button
    - search.suggest # search suggestions: https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
    - search.highlight # highlight search term on target page: https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky # stick navigation tabs below header while scrolling
    - navigation.tracking
    - navigation.path
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "black"
      accent: "grey"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: static/img/k3d_logo_black_green.svg
  favicon: static/img/favicons_black_blue/favicon.png
  icon:
    repo: fontawesome/brands/github

# Navigation
# nav: omitted, because we're using the awesome-pages plugin (https://squidfunk.github.io/mkdocs-material/plugins/awesome-pages/)

# Extensions
markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - admonition # https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - pymdownx.highlight: # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight
      use_pygments: true
  - pymdownx.inlinehilite # https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#inlinehilite
  - pymdownx.superfences # https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#superfences
  - pymdownx.tabbed # https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#tabbed
  - pymdownx.details # https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#details
  - pymdownx.emoji: # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#configuration
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - smarty # https://python-markdown.github.io/extensions/smarty/
  - mdx_truly_sane_lists # https://github.com/radude/mdx_truly_sane_lists -> proper indentation of md list items

# Plugins
plugins:
  - search
  - git-revision-date-localized: # https://squidfunk.github.io/mkdocs-material/plugins/revision-date/
      type: date
  - awesome-pages # https://squidfunk.github.io/mkdocs-material/plugins/awesome-pages/
  - include-markdown # https://github.com/mondeja/mkdocs-include-markdown-plugin
  - mike: # Versioned Docs: https://github.com/jimporter/mike
      version_selector: true   # set to false to leave out the version selector
      css_dir: static/css             # the directory to put the version selector's CSS
      javascript_dir: static/js       # the directory to put the version selector's JS
      canonical_version: null  # the version for <link rel="canonical">; `null` uses the version specified via `mike deploy`

# Extra mkdocs-material settings
extra:
  version:
    provider: mike

# Other Settings
strict: true # halt processing when a warning is raised
